module.exports = {
  "Log_In": require('./locator.RM0MIrnV3NzcKQdy.json'),
  "CREATE_ACCOUNT": require('./locator.8v4mXncSDKcbI1z5.json'),
  "First_Name": require('./locator.0OLwpoHwqNpQ74ZH.json'),
  "Last_Name": require('./locator.121jnYUenVQXEDTl.json'),
  "User_Id": require('./locator.RTVfvZiU3NKg5yhb.json'),
  "Password": require('./locator.xphnX5tf03xXgfrT.json'),
  "Admin_Account": require('./locator.wVliLmdW8BRD4b2D.json'),
  "SUBMIT": require('./locator.IvOFw8WJ4TnvKUvW.json'),
  "[id='formLoginUserName']": require('./locator.fGOW2OfjxIueGq8u.json'),
  "[id='formLoginPassword']": require('./locator.NIR57kPdSUEOcYjP.json'),
  "SIGN_IN": require('./locator.IWwXGQNZ5X3UlNEK.json'),
  "Home": require('./locator.H3Ne2REQ6dExvoWy.json'),
  "Log_Out": require('./locator.GVe6lsR600fdQKTB.json'),
  "QrMyHPsquCMWj2kp": require('./locator.QrMyHPsquCMWj2kp.json'),
  ".Products_>_:nth-child(1)_.MuiSvgIc": require('./locator.HqSFFSnGCPCop7pp.json'),
  "ADD_TO_CART": require('./locator.YWP6ZjlccG1SdfPv.json'),
  "Cart:_3": require('./locator.Auz6iz74xI3yjOs2.json'),
  "cartQuantity": require('./locator.hazhcVNz6V9XQT7p.json'),
  ".shoppingCartCards_>_:nth-child(1)_": require('./locator.D2Awy5fwBMfNVO3T.json'),
  "CHECKOUT": require('./locator.0NThRXn6csghMjMQ.json'),
  "PURCHASE": require('./locator.rIkmcK4QfiuRhpZY.json'),
};